/*
Copyright (c) 2015 chrono
This software is released under the MIT License.
http://opensource.org/licenses/mit-license.php
*/
#ifndef	__LIBGDK_PIXBUF_200__
#define	global	__LIBGDK_PIXBUF_200__

#uselib "libgdk_pixbuf-2.0-0.dll"
;#func global gdk_colorspace_get_type "" 
;#func global gdk_interp_type_get_type "" 
;#func global gdk_pixbuf_add_alpha "" 
;#func global gdk_pixbuf_alpha_mode_get_type "" 
;#func global gdk_pixbuf_animation_get_height "" 
;#func global gdk_pixbuf_animation_get_iter "" 
;#func global gdk_pixbuf_animation_get_static_image "" 
;#func global gdk_pixbuf_animation_get_type "" 
;#func global gdk_pixbuf_animation_get_width "" 
;#func global gdk_pixbuf_animation_is_static_image "" 
;#func global gdk_pixbuf_animation_iter_advance "" 
;#func global gdk_pixbuf_animation_iter_get_delay_time "" 
;#func global gdk_pixbuf_animation_iter_get_pixbuf "" 
;#func global gdk_pixbuf_animation_iter_get_type "" 
;#func global gdk_pixbuf_animation_iter_on_currently_loading_frame "" 
;#func global gdk_pixbuf_animation_new_from_file "" 
;#func global gdk_pixbuf_animation_new_from_file_utf8 "" 
;#func global gdk_pixbuf_animation_ref "" 
;#func global gdk_pixbuf_animation_unref "" 
;#func global gdk_pixbuf_apply_embedded_orientation "" 
;#func global gdk_pixbuf_composite "" 
;#func global gdk_pixbuf_composite_color "" 
;#func global gdk_pixbuf_composite_color_simple "" 
;#func global gdk_pixbuf_copy "" 
;#func global gdk_pixbuf_copy_area "" 
;#func global gdk_pixbuf_error_get_type "" 
;#func global gdk_pixbuf_error_quark "" 
;#func global gdk_pixbuf_fill "" 
;#func global gdk_pixbuf_flip "" 
;#func global gdk_pixbuf_format_copy "" 
;#func global gdk_pixbuf_format_free "" 
;#func global gdk_pixbuf_format_get_description "" 
;#func global gdk_pixbuf_format_get_extensions "" 
;#func global gdk_pixbuf_format_get_license "" 
;#func global gdk_pixbuf_format_get_mime_types "" 
;#func global gdk_pixbuf_format_get_name "" 
;#func global gdk_pixbuf_format_get_type "" 
;#func global gdk_pixbuf_format_is_disabled "" 
;#func global gdk_pixbuf_format_is_scalable "" 
;#func global gdk_pixbuf_format_is_writable "" 
;#func global gdk_pixbuf_format_set_disabled "" 
;#func global gdk_pixbuf_from_pixdata "" 
;#func global gdk_pixbuf_get_bits_per_sample "" 
;#func global gdk_pixbuf_get_byte_length "" 
;#func global gdk_pixbuf_get_colorspace "" 
;#func global gdk_pixbuf_get_file_info "" 
;#func global gdk_pixbuf_get_formats "" 
;#func global gdk_pixbuf_get_has_alpha "" 
;#func global gdk_pixbuf_get_height "" 
;#func global gdk_pixbuf_get_n_channels "" 
;#func global gdk_pixbuf_get_option "" 
;#func global gdk_pixbuf_get_pixels "" 
;#func global gdk_pixbuf_get_pixels_with_length "" 
;#func global gdk_pixbuf_get_rowstride "" 
#func global gdk_pixbuf_get_type "gdk_pixbuf_get_type"
;#func global gdk_pixbuf_get_width "" 
;#func global gdk_pixbuf_gettext "" 
;#func global gdk_pixbuf_loader_close "" 
;#func global gdk_pixbuf_loader_get_animation "" 
;#func global gdk_pixbuf_loader_get_format "" 
;#func global gdk_pixbuf_loader_get_pixbuf "" 
;#func global gdk_pixbuf_loader_get_type "" 
;#func global gdk_pixbuf_loader_new "" 
;#func global gdk_pixbuf_loader_new_with_mime_type "" 
;#func global gdk_pixbuf_loader_new_with_type "" 
;#func global gdk_pixbuf_loader_set_size "" 
;#func global gdk_pixbuf_loader_write "" 
;#func global gdk_pixbuf_major_version "" 
;#func global gdk_pixbuf_micro_version "" 
;#func global gdk_pixbuf_minor_version "" 
;#func global gdk_pixbuf_new "" 
;#func global gdk_pixbuf_new_from_data "" 
#func global gdk_pixbuf_new_from_file "gdk_pixbuf_new_from_file" str, sptr
;#func global gdk_pixbuf_new_from_file_at_scale "" 
;#func global gdk_pixbuf_new_from_file_at_scale_utf8 "" 
;#func global gdk_pixbuf_new_from_file_at_size "" 
;#func global gdk_pixbuf_new_from_file_at_size_utf8 "" 
;#func global gdk_pixbuf_new_from_file_utf8 "" 
;#func global gdk_pixbuf_new_from_inline "" 
;#func global gdk_pixbuf_new_from_resource "" 
;#func global gdk_pixbuf_new_from_resource_at_scale "" 
;#func global gdk_pixbuf_new_from_stream "" 
;#func global gdk_pixbuf_new_from_stream_async "" 
;#func global gdk_pixbuf_new_from_stream_at_scale "" 
;#func global gdk_pixbuf_new_from_stream_at_scale_async "" 
;#func global gdk_pixbuf_new_from_stream_finish "" 
;#func global gdk_pixbuf_new_from_xpm_data "" 
;#func global gdk_pixbuf_new_subpixbuf "" 
;#func global gdk_pixbuf_non_anim_get_type "" 
;#func global gdk_pixbuf_non_anim_new "" 
;#func global gdk_pixbuf_ref "" 
;#func global gdk_pixbuf_rotate_simple "" 
;#func global gdk_pixbuf_rotation_get_type "" 
;#func global gdk_pixbuf_saturate_and_pixelate "" 
;#func global gdk_pixbuf_save "" 
;#func global gdk_pixbuf_save_to_buffer "" 
;#func global gdk_pixbuf_save_to_bufferv "" 
;#func global gdk_pixbuf_save_to_callback "" 
;#func global gdk_pixbuf_save_to_callbackv "" 
;#func global gdk_pixbuf_save_to_stream "" 
;#func global gdk_pixbuf_save_to_stream_async "" 
;#func global gdk_pixbuf_save_to_stream_finish "" 
;#func global gdk_pixbuf_save_utf8 "" 
;#func global gdk_pixbuf_savev "" 
;#func global gdk_pixbuf_savev_utf8 "" 
;#func global gdk_pixbuf_scale "" 
;#func global gdk_pixbuf_scale_simple "" 
;#func global gdk_pixbuf_scaled_anim_get_type "" 
;#func global gdk_pixbuf_scaled_anim_iter_get_type "" 
;#func global gdk_pixbuf_set_option "" 
;#func global gdk_pixbuf_simple_anim_add_frame "" 
;#func global gdk_pixbuf_simple_anim_get_loop "" 
;#func global gdk_pixbuf_simple_anim_get_type "" 
;#func global gdk_pixbuf_simple_anim_iter_get_type "" 
;#func global gdk_pixbuf_simple_anim_new "" 
;#func global gdk_pixbuf_simple_anim_set_loop "" 
;#func global gdk_pixbuf_unref "" 
;#func global gdk_pixbuf_version "" 
;#func global gdk_pixdata_deserialize "" 
;#func global gdk_pixdata_from_pixbuf "" 
;#func global gdk_pixdata_serialize "" 
;#func global gdk_pixdata_to_csource "" 

#include "libgtk-3-0.as"
   gtk_init 0, 0
   gdk_pixbuf_get_type
   GDK_TYPE_PIXBUF	= stat

#endif
